version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devopsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/devopsdb
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: