name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  BACKEND_REPO: python-microservice-app
  FRONTEND_REPO: react-frontend-app

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # -------- BACKEND IMAGE --------
      - name: Build Backend Image
        run: |
          docker build -t $BACKEND_REPO:$IMAGE_TAG ./backend

      - name: Tag Backend Image
        run: |
          docker tag $BACKEND_REPO:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:$IMAGE_TAG

      - name: Push Backend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:$IMAGE_TAG

      # -------- FRONTEND IMAGE --------
      - name: Build Frontend Image
        run: |
          docker build -t $FRONTEND_REPO:$IMAGE_TAG ./frontend

      - name: Tag Frontend Image
        run: |
          docker tag $FRONTEND_REPO:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:$IMAGE_TAG

      - name: Push Frontend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:$IMAGE_TAG