name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  BACKEND_REPO: python-microservice-app
  FRONTEND_REPO: react-frontend-app
  GITOPS_REPO: eks-gitops-deployments

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV


      ################################
      # Build and Push Backend Image
      ################################

      - name: Build Backend Image
        run: |
          docker build -t $BACKEND_REPO:$IMAGE_TAG ./backend

      - name: Tag Backend Image
        run: |
          docker tag $BACKEND_REPO:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:$IMAGE_TAG

      - name: Push Backend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:$IMAGE_TAG


      ################################
      # Build and Push Frontend Image
      ################################

      - name: Build Frontend Image
        run: |
          docker build -t $FRONTEND_REPO:$IMAGE_TAG ./frontend

      - name: Tag Frontend Image
        run: |
          docker tag $FRONTEND_REPO:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:$IMAGE_TAG

      - name: Push Frontend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:$IMAGE_TAG


      ################################
      # Update GitOps Repo
      ################################

      - name: Update GitOps repo with new image tag
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |

          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/rasika-08061998/$GITOPS_REPO.git
          cd $GITOPS_REPO/backend

          sed -i "s|image: .*|image: 528757804354.dkr.ecr.ap-south-1.amazonaws.com/python-microservice-app:${IMAGE_TAG}|g" deployment.yaml

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

          git add deployment.yaml

          git commit -m "Update backend image to ${IMAGE_TAG}" || echo "No changes to commit"

          git push